import React from "react";
import { Button } from "../components/ui/button";
import { useNavigate } from "react-router-dom";

const HeroSection: React.FC = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: "🧠",
      title: "AI-Powered Suggestions",
      description:
        "Get intelligent ideas generated by AI to expand your thoughts",
    },
    {
      icon: " 🎨",
      title: "Visual Customization",
      description:
        "Customize colors, styles, and layouts to match your thinking style",
    },
    {
      icon: "📱",
      title: "Real-time Collaboration",
      description: "Work together with your team in real-time (coming soon)",
    },
    {
      icon: "📤",
      title: "Easy Export",
      description: "Export your mind maps as PNG, PDF, or JSON files",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800">
      {/* Navigation */}
      <nav className="container mx-auto px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] flex items-center justify-center">
              <span className="text-white font-bold text-xl">M</span>
            </div>
            <span className="text-2xl font-bold bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] bg-clip-text text-transparent">
              MindMapX
            </span>
          </div>
        </div>
      </nav>

      {/* Hero Content */}
      <div className="container mx-auto px-6 py-20">
        <div className="flex flex-col lg:flex-row items-center justify-between">
          <div className="lg:w-1/2 mb-12 lg:mb-0">
            <h1 className="text-5xl lg:text-6xl font-bold text-gray-900 dark:text-white mb-6">
              Visualize Your{" "}
              <span className="bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] bg-clip-text text-transparent">
                Ideas
              </span>{" "}
              with AI
            </h1>
            <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
              Transform your thoughts into beautiful, interactive mind maps.
              Collaborate in real-time, get AI-powered suggestions, and bring
              your ideas to life.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button
                onClick={() => navigate("/mindmap")}
                size="lg"
                className="bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] text-white hover:opacity-90 px-8 py-6 text-lg"
              >
                Start Creating Free
              </Button>
            </div>

            <div className="mt-12 flex items-center space-x-8">
              <div>
                <div className="text-3xl font-bold text-gray-900 dark:text-white">
                  10K+
                </div>
                <div className="text-gray-600 dark:text-gray-400">
                  Active Users
                </div>
              </div>
              <div>
                <div className="text-3xl font-bold text-gray-900 dark:text-white">
                  50K+
                </div>
                <div className="text-gray-600 dark:text-gray-400">
                  Mind Maps Created
                </div>
              </div>
              <div>
                <div className="text-3xl font-bold text-gray-900 dark:text-white">
                  4.9★
                </div>
                <div className="text-gray-600 dark:text-gray-400">
                  User Rating
                </div>
              </div>
            </div>
          </div>

          <div className="lg:w-1/2">
            <div className="relative">
              <div className="absolute -top-6 -left-6 w-64 h-64 bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] rounded-full opacity-10 blur-3xl"></div>
              <div className="absolute -bottom-6 -right-6 w-64 h-64 bg-gradient-to-r from-[#4ECDC4] to-[#2C7873] rounded-full opacity-10 blur-3xl"></div>

              <div className="relative bg-white dark:bg-gray-800 rounded-3xl shadow-2xl p-8 border border-gray-200 dark:border-gray-700">
                <div className="flex items-center justify-between mb-6">
                  <div className="flex items-center space-x-2">
                    <div className="w-3 h-3 rounded-full bg-red-500"></div>
                    <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                    <div className="w-3 h-3 rounded-full bg-green-500"></div>
                  </div>
                  <span className="text-sm font-medium text-gray-600 dark:text-gray-400">
                    Sample Mind Map
                  </span>
                </div>

                {/* Mock mind map visualization */}
                <div className="relative h-96">
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                    <div className="w-32 h-24 rounded-xl bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] flex items-center justify-center">
                      <span className="text-white font-bold">Central Idea</span>
                    </div>
                  </div>

                  {[0, 1, 2, 3].map((i) => {
                    const angle = (i * Math.PI) / 2;
                    const x = Math.cos(angle) * 120;
                    const y = Math.sin(angle) * 120;
                    const colors = ["#4ECDC4", "#45B7D1", "#96CEB4", "#FFEAA7"];

                    return (
                      <div
                        key={i}
                        className="absolute"
                        style={{
                          left: `calc(50% + ${x}px)`,
                          top: `calc(50% + ${y}px)`,
                        }}
                      >
                        <div className="relative">
                          <div className="absolute -inset-4 bg-gradient-to-r from-gray-200 to-gray-300 dark:from-gray-700 dark:to-gray-800 rounded-full blur-md opacity-50"></div>
                          <div
                            className="w-20 h-16 rounded-lg flex items-center justify-center relative z-10"
                            style={{ backgroundColor: colors[i] }}
                          >
                            <span className="text-white text-sm font-medium px-2 text-center">
                              Idea {i + 1}
                            </span>
                          </div>
                        </div>
                      </div>
                    );
                  })}

                  {/* Connecting lines */}
                  <svg
                    className="absolute inset-0 w-full h-full"
                    style={{ pointerEvents: "none" }}
                  >
                    {[0, 1, 2, 3].map((i) => {
                      const angle = (i * Math.PI) / 2;
                      const x1 = 160;
                      const y1 = 192;
                      const x2 = 160 + Math.cos(angle) * 120;
                      const y2 = 192 + Math.sin(angle) * 120;

                      return (
                        <line
                          key={i}
                          x1={x1}
                          y1={y1}
                          x2={x2}
                          y2={y2}
                          stroke="#BF4E30"
                          strokeWidth="2"
                          strokeDasharray="5,3"
                        />
                      );
                    })}
                  </svg>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="container mx-auto px-6 py-20">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
            Everything You Need to{" "}
            <span className="bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] bg-clip-text text-transparent">
              Organize Thoughts
            </span>
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
            Powerful features designed to enhance your brainstorming and
            planning process
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div
              key={index}
              className="bg-white dark:bg-gray-800 rounded-2xl p-6 border border-gray-200 dark:border-gray-700 hover:shadow-xl transition-all duration-300 hover:-translate-y-2"
            >
              <div className="text-4xl mb-4">{feature.icon}</div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3">
                {feature.title}
              </h3>
              <p className="text-gray-600 dark:text-gray-400">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* CTA Section */}
      <div className="container mx-auto px-6 py-20">
        <div className="bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] rounded-3xl p-12 text-center">
          <h2 className="text-4xl font-bold text-white mb-6">
            Ready to Transform Your Ideas?
          </h2>
          <p className="text-xl text-white opacity-90 mb-8 max-w-2xl mx-auto">
            Join thousands of users who are already creating amazing mind maps
            with AI assistance
          </p>
          <Button
            onClick={() => navigate("/mindmap")}
            size="lg"
            className="bg-white text-[#F05A5B] hover:bg-gray-100 px-10 py-6 text-lg font-semibold rounded-full"
          >
            Get Started For Free
          </Button>
          <p className="text-white opacity-80 mt-4 text-sm">
            No credit card required • Free forever plan
          </p>
        </div>
      </div>
    </div>
  );
};

export default HeroSection;
