import React from "react";
import { Button } from "../components/ui/button";
import { useNavigate } from "react-router-dom";

const HeroSection: React.FC = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: "🧠",
      title: "AI-Powered Suggestions",
      description:
        "Get intelligent ideas generated by AI to expand your thoughts",
    },
    {
      icon: "🎨",
      title: "Visual Customization",
      description:
        "Customize colors, styles, and layouts to match your thinking style",
    },
    {
      icon: "📱",
      title: "Real-time Collaboration",
      description: "Work together with your team in real-time (coming soon)",
    },
    {
      icon: "📤",
      title: "Easy Export",
      description: "Export your mind maps as PNG, PDF, or JSON files",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800">
      {/* Navigation */}
      <nav className="container mx-auto px-4 sm:px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-xl bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] flex items-center justify-center">
              <span className="text-white font-bold text-lg sm:text-xl">M</span>
            </div>
            <span className="text-xl sm:text-2xl font-bold bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] bg-clip-text text-transparent">
              MindMapX
            </span>
          </div>
        </div>
      </nav>

      {/* Hero Content */}
      <div className="container mx-auto px-4 sm:px-6 py-12 md:py-20">
        <div className="flex flex-col lg:flex-row items-center justify-between gap-8">
          <div className="lg:w-1/2">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 dark:text-white mb-4 sm:mb-6">
              Visualize Your{" "}
              <span className="bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] bg-clip-text text-transparent">
                Ideas
              </span>{" "}
              with AI
            </h1>
            <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 mb-6 sm:mb-8">
              Transform your thoughts into beautiful, interactive mind maps.
              Collaborate in real-time, get AI-powered suggestions, and bring
              your ideas to life.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 sm:gap-4">
              <Button
                onClick={() => navigate("/mindmap")}
                size="lg"
                className="bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] text-white hover:opacity-90 px-6 sm:px-8 py-5 sm:py-6 text-base sm:text-lg w-full sm:w-auto"
              >
                Start Creating Free
              </Button>
            </div>

            <div className="mt-8 sm:mt-12 flex flex-wrap items-center gap-6 sm:gap-8">
              <div>
                <div className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white">
                  10K+
                </div>
                <div className="text-sm sm:text-base text-gray-600 dark:text-gray-400">
                  Active Users
                </div>
              </div>
              <div>
                <div className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white">
                  50K+
                </div>
                <div className="text-sm sm:text-base text-gray-600 dark:text-gray-400">
                  Mind Maps Created
                </div>
              </div>
              <div>
                <div className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white">
                  4.9★
                </div>
                <div className="text-sm sm:text-base text-gray-600 dark:text-gray-400">
                  User Rating
                </div>
              </div>
            </div>
          </div>

          <div className="lg:w-1/2 w-full">
            <div className="relative">
              <div className="absolute -top-4 -left-4 w-48 h-48 sm:w-64 sm:h-64 bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] rounded-full opacity-10 blur-3xl"></div>
              <div className="absolute -bottom-4 -right-4 w-48 h-48 sm:w-64 sm:h-64 bg-gradient-to-r from-[#4ECDC4] to-[#2C7873] rounded-full opacity-10 blur-3xl"></div>

              <div className="relative bg-white dark:bg-gray-800 rounded-2xl sm:rounded-3xl shadow-xl sm:shadow-2xl p-6 sm:p-8 border border-gray-200 dark:border-gray-700">
                <div className="flex items-center justify-between mb-4 sm:mb-6">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 sm:w-3 sm:h-3 rounded-full bg-red-500"></div>
                    <div className="w-2 h-2 sm:w-3 sm:h-3 rounded-full bg-yellow-500"></div>
                    <div className="w-2 h-2 sm:w-3 sm:h-3 rounded-full bg-green-500"></div>
                  </div>
                  <span className="text-xs sm:text-sm font-medium text-gray-600 dark:text-gray-400">
                    Sample Mind Map
                  </span>
                </div>

                {/* Mock mind map visualization */}
                <div className="relative h-64 sm:h-80 md:h-96">
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                    <div className="w-24 h-20 sm:w-32 sm:h-24 rounded-lg sm:rounded-xl bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] flex items-center justify-center p-2">
                      <span className="text-white font-bold text-sm sm:text-base">
                        Central Idea
                      </span>
                    </div>
                  </div>

                  {[0, 1, 2, 3].map((i) => {
                    const angle = (i * Math.PI) / 2;
                    const radius = 90;
                    const x = Math.cos(angle) * radius;
                    const y = Math.sin(angle) * radius;
                    const colors = ["#4ECDC4", "#45B7D1", "#96CEB4", "#FFEAA7"];

                    return (
                      <div
                        key={i}
                        className="absolute"
                        style={{
                          left: `calc(50% + ${x}px)`,
                          top: `calc(50% + ${y}px)`,
                        }}
                      >
                        <div className="relative">
                          <div className="absolute -inset-3 sm:-inset-4 bg-gradient-to-r from-gray-200 to-gray-300 dark:from-gray-700 dark:to-gray-800 rounded-full blur-md opacity-50"></div>
                          <div
                            className="w-16 h-14 sm:w-20 sm:h-16 rounded-md sm:rounded-lg flex items-center justify-center relative z-10"
                            style={{ backgroundColor: colors[i] }}
                          >
                            <span className="text-white text-xs sm:text-sm font-medium px-2 text-center">
                              Idea {i + 1}
                            </span>
                          </div>
                        </div>
                      </div>
                    );
                  })}

                  {/* Connecting lines */}
                  <svg
                    className="absolute inset-0 w-full h-full"
                    style={{ pointerEvents: "none" }}
                  >
                    {[0, 1, 2, 3].map((i) => {
                      const angle = (i * Math.PI) / 2;
                      const centerX = 50;
                      const centerY = 50;
                      const radius = 35;
                      const x1 = centerX;
                      const y1 = centerY;
                      const x2 = centerX + Math.cos(angle) * radius;
                      const y2 = centerY + Math.sin(angle) * radius;

                      return (
                        <line
                          key={i}
                          x1={`${x1}%`}
                          y1={`${y1}%`}
                          x2={`${x2}%`}
                          y2={`${y2}%`}
                          stroke="#BF4E30"
                          strokeWidth="2"
                          strokeDasharray="5,3"
                        />
                      );
                    })}
                  </svg>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section - Updated UI */}
      <div className="container mx-auto px-4 sm:px-6 py-12 md:py-20">
        <div className="text-center mb-12 md:mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-3 sm:mb-4">
            Everything You Need to{" "}
            <span className="bg-gradient-to-r from-[#4ECDC4] to-[#2C7873] bg-clip-text text-transparent">
              Organize Thoughts
            </span>
          </h2>
          <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
            Powerful features designed to enhance your brainstorming and
            planning process
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 sm:gap-8">
          {features.map((feature, index) => (
            <div
              key={index}
              className="group bg-white dark:bg-gray-800 rounded-xl sm:rounded-2xl p-5 sm:p-6 border border-gray-200 dark:border-gray-700 hover:shadow-xl transition-all duration-300 hover:-translate-y-2 hover:border-transparent hover:bg-gradient-to-br hover:from-white hover:to-gray-50 dark:hover:from-gray-800 dark:hover:to-gray-900"
            >
              <div className="text-3xl sm:text-4xl mb-3 sm:mb-4 group-hover:scale-110 transition-transform duration-300">
                {feature.icon}
              </div>
              <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white mb-2 sm:mb-3">
                {feature.title}
              </h3>
              <p className="text-sm sm:text-base text-gray-600 dark:text-gray-400">
                {feature.description}
              </p>
              <div className="mt-4 pt-4 border-t border-gray-100 dark:border-gray-700">
                <span className="text-xs sm:text-sm text-[#4ECDC4] font-medium">
                  Learn more →
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Benefits Section - New 3rd section */}
      <div className="container mx-auto px-4 sm:px-6 py-12 md:py-20">
        <div className="text-center mb-12 md:mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-3 sm:mb-4">
            Why Choose{" "}
            <span className="bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] bg-clip-text text-transparent">
              MindMapX
            </span>
          </h2>
          <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
            Experience the next generation of mind mapping tools
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
          <div className="space-y-6">
            <div className="bg-gradient-to-r from-white to-gray-50 dark:from-gray-800 dark:to-gray-900 rounded-2xl p-6 border border-gray-200 dark:border-gray-700">
              <div className="flex items-start space-x-4">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-[#4ECDC4] to-[#2C7873] flex items-center justify-center">
                  <span className="text-white text-lg">⚡</span>
                </div>
                <div>
                  <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">
                    Lightening Fast
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    Create and edit mind maps in real-time with no lag or
                    delays. Our optimized engine handles even the most complex
                    maps effortlessly.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-r from-white to-gray-50 dark:from-gray-800 dark:to-gray-900 rounded-2xl p-6 border border-gray-200 dark:border-gray-700">
              <div className="flex items-start space-x-4">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] flex items-center justify-center">
                  <span className="text-white text-lg">🔒</span>
                </div>
                <div>
                  <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">
                    Enterprise Security
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    Your data is encrypted end-to-end. We follow industry best
                    practices to ensure your mind maps are safe and private.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-r from-white to-gray-50 dark:from-gray-800 dark:to-gray-900 rounded-2xl p-6 border border-gray-200 dark:border-gray-700">
              <div className="flex items-start space-x-4">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-[#45B7D1] to-[#96CEB4] flex items-center justify-center">
                  <span className="text-white text-lg">📊</span>
                </div>
                <div>
                  <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">
                    Advanced Analytics
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    Gain insights into your thought process with visual
                    analytics and connection patterns.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="relative">
            <div className="relative bg-white dark:bg-gray-800 rounded-2xl p-6 border border-gray-200 dark:border-gray-700 shadow-xl">
              <div className="aspect-video rounded-lg overflow-hidden bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 flex items-center justify-center">
                <div className="text-center p-8">
                  <div className="text-6xl mb-4">📈</div>
                  <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                    Performance Metrics
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    Visualize your productivity and creativity patterns
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-3 gap-4 mt-6">
                <div className="text-center">
                  <div className="text-2xl font-bold text-[#4ECDC4]">98%</div>
                  <div className="text-sm text-gray-600 dark:text-gray-400">
                    Satisfaction
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-[#F05A5B]">3.5x</div>
                  <div className="text-sm text-gray-600 dark:text-gray-400">
                    Productivity
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-[#45B7D1]">24/7</div>
                  <div className="text-sm text-gray-600 dark:text-gray-400">
                    Support
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-300 pt-12 pb-8">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="md:col-span-1">
              <div className="flex items-center space-x-2 mb-4">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] flex items-center justify-center">
                  <span className="text-white font-bold text-xl">M</span>
                </div>
                <span className="text-2xl font-bold bg-gradient-to-r from-[#F05A5B] to-[#BF4E30] bg-clip-text text-transparent">
                  MindMapX
                </span>
              </div>
              <p className="text-gray-400 mb-4">
                Transform your thoughts into beautiful, interactive mind maps.
              </p>
              <div className="flex space-x-4">
                <a
                  href="#"
                  className="text-gray-400 hover:text-white transition-colors"
                >
                  <span className="sr-only">Twitter</span>
                  <svg
                    className="w-6 h-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
                  </svg>
                </a>
                <a
                  href="#"
                  className="text-gray-400 hover:text-white transition-colors"
                >
                  <span className="sr-only">GitHub</span>
                  <svg
                    className="w-6 h-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      fillRule="evenodd"
                      d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                      clipRule="evenodd"
                    />
                  </svg>
                </a>
                <a
                  href="#"
                  className="text-gray-400 hover:text-white transition-colors"
                >
                  <span className="sr-only">LinkedIn</span>
                  <svg
                    className="w-6 h-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      fillRule="evenodd"
                      d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"
                    />
                  </svg>
                </a>
              </div>
            </div>

            <div>
              <h3 className="text-white font-bold text-lg mb-4">Product</h3>
              <ul className="space-y-2">
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Features
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Pricing
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Templates
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    API
                  </a>
                </li>
              </ul>
            </div>

            <div>
              <h3 className="text-white font-bold text-lg mb-4">Company</h3>
              <ul className="space-y-2">
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    About
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Blog
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Careers
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Contact
                  </a>
                </li>
              </ul>
            </div>

            <div>
              <h3 className="text-white font-bold text-lg mb-4">Resources</h3>
              <ul className="space-y-2">
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Documentation
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Help Center
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Community
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:text-white transition-colors">
                    Status
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-500 text-sm">
            <p>© {new Date().getFullYear()} MindMapX. All rights reserved.</p>
            <div className="mt-2 flex flex-wrap justify-center gap-4">
              <a href="#" className="hover:text-gray-300 transition-colors">
                Privacy Policy
              </a>
              <a href="#" className="hover:text-gray-300 transition-colors">
                Terms of Service
              </a>
              <a href="#" className="hover:text-gray-300 transition-colors">
                Cookie Policy
              </a>
              <a href="#" className="hover:text-gray-300 transition-colors">
                Sitemap
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default HeroSection;
